### ISSUE TITLE
[Portuguese] Mudanças de texto e chamada para whatsapp

### ISSUE THREAD

**Issue by alexanmtz** [casasdepraia/casadepraiaporto#15]
Para otimizar as campanhas e aproveitar o período pensei em mudarmos por enquanto o texto da Home:

H1: Alugue um apartamento mobiliado para o carnaval em Porto Seguro
H2: Fique hospedado em um condomínio fechado próximo ao Axé Moi

Botão da home mudar para: 'Quero consultar valores e datas' e direcionar direto para o Whats https://api.whatsapp.com/send?phone=5531994367564

E por fim acrescentar um botão que fique por cima do site, no canto direito. Usando essa referência; https://adscursos.com.br/

Também deverão ser feitas as seguintes alterações:
- Botão do Github na barra de links para redes sociais deverá ser retirado
- Você deverá adicionar um campo no formulário de envio de contato um novo campo de telefone (usando uma máscara para validação de número de telefone, de forma que o usuário preencha o telefone no formato correto)
- O mais alto que puder no Head, você vai colocar o script abaixo:
```
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-KZPP245');</script>
```
E na abertura do body, colcoca esse outro código:
```
<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KZPP245" height="0" width="0" style="display:none;visibility:hidden"></iframe>
```

### O que você precisa saber
- Github Pages
- Edição HTML / CSS

### Nível 
Iniciante

### Referências
- https://jekyllrb.com/
- https://github.com/worknenjoy/airspace-jekyll

### Como iniciar
- Criar um fork do projeto
- Criar uma nova branch `git checkout -b issue-3`
- Rodar o projeto localmente com `bundle exec jekyll serve`
- Abrir no endereço `http: // localhost: 4000`
- Realizar as modificações requisitadas
- Testar as modificações
- Fazer um commit
- Enviar a branch remotamente `git push origin issue-3`
- Criar um Pull Request

Qualquer dúvida, fique a vontade para comentar que ajudaremos :+1:

**Comment by VictorAlessander** [comment]
https://github.com/casasdepraia/casadepraiaporto/pull/17

**Comment by alexanmtz** [comment]
#17 merged so we can close this issue, thanks for the contribution @VictorAlessander 🎉
