### ISSUE TITLE
[Portuguese] Botão do menu principal não funciona no mobile

### ISSUE THREAD

**Issue by alexanmtz** [casasdepraia/casadepraiaporto#18]
Depois que a issue #15 foi fechada, um novo bug surgiu, impedindo que seja possível clicar no menu

### Screenshot
<img width="491" alt="Screenshot 2020-03-09 at 18 42 01" src="https://user-images.githubusercontent.com/88840/76241856-f287db80-6235-11ea-879f-4c0d2fcd4bd9.png">

### O que você precisa saber
- Github Pages
- Edição HTML / CSS

### Nível 
Iniciante

### Referências
- https://jekyllrb.com/
- https://github.com/worknenjoy/airspace-jekyll

### Como iniciar
- Criar um fork do projeto
- Criar uma nova branch `git checkout -b issue-3`
- Rodar o projeto localmente com `bundle exec jekyll serve`
- Abrir no endereço `http: // localhost: 4000`
- Realizar as modificações requisitadas
- Testar as modificações
- Fazer um commit
- Enviar a branch remotamente `git push origin issue-3`
- Criar um Pull Request

Qualquer dúvida, fique a vontade para comentar que ajudaremos :+1:

**Comment by alexanmtz** [comment]
@VictorAlessander pode dar uma olhada nessa issue que veio depois que integramos as últimas mudanças?

**Comment by VictorAlessander** [comment]
Com certeza. Em breve darei um retorno.

**Comment by VictorAlessander** [comment]
Será resolvido no PR https://github.com/casasdepraia/casadepraiaporto/pull/19

@alexanmtz peço perdão pelo erro causado por mim.

**Comment by alexanmtz** [comment]
merged with #19
